// src/react/DialRoot.tsx
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { DialStore } from '../core';
import type { PanelConfig } from '../core';
import { Panel } from './Panel';

export type DialPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';

interface DialRootProps {
  position?: DialPosition;
}

export function DialRoot({ position = 'top-right' }: DialRootProps) {
  const [panels, setPanels] = useState<PanelConfig[]>([]);
  const [mounted, setMounted] = useState(false);

  // Subscribe to global panel changes
  useEffect(() => {
    setMounted(true);
    setPanels(DialStore.getPanels());

    const unsubscribe = DialStore.subscribeGlobal(() => {
      setPanels(DialStore.getPanels());
    });

    return unsubscribe;
  }, []);

  // Don't render on server
  if (!mounted || typeof window === 'undefined') {
    return null;
  }

  // Don't render if no panels registered
  if (panels.length === 0) {
    return null;
  }

  const content = (
    <div className="dialkit-root">
      <div className="dialkit-panel" data-position={position}>
        {panels.map((panel) => (
          <Panel key={panel.id} panel={panel} />
        ))}
      </div>
    </div>
  );

  return createPortal(content, document.body);
}

// src/solid/components/DialRoot.tsx
import { createSignal, onMount, onCleanup, Show, For } from 'solid-js';
import { Portal } from 'solid-js/web';
import { DialStore } from '../../store/DialStore';
import type { PanelConfig } from '../../store/DialStore';
import { Panel } from './Panel';

export type DialPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';

interface DialRootProps {
  position?: DialPosition;
}

export function DialRoot(props: DialRootProps) {
  const [panels, setPanels] = createSignal<PanelConfig[]>([]);
  const [mounted, setMounted] = createSignal(false);

  onMount(() => {
    setMounted(true);
    setPanels(DialStore.getPanels());
    const unsub = DialStore.subscribeGlobal(() => {
      setPanels(DialStore.getPanels());
    });
    onCleanup(unsub);
  });

  return (
    <Show when={mounted() && typeof window !== 'undefined' && panels().length > 0}>
      <Portal mount={document.body}>
        <div class="dialkit-root">
          <div class="dialkit-panel" data-position={props.position ?? 'top-right'}>
            <For each={panels()}>
              {(panel) => <Panel panel={panel} />}
            </For>
          </div>
        </div>
      </Portal>
    </Show>
  );
}
